
author = "Carlo Cordes"
title = "Bayesian Neural Networks for Wildfire Prediction"
graduation-year = 2026
graduation-month = "June"
supervisor1 = "Dr. Azarakhsh Rafiee"
supervisor2 = "Justin Schembrie"
coreader    = "yet to be determined"
graduation-group = "3D geoinformation group"
#graduation-group = "Geo-Database Management Centre"

